name: Payment Gateway CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: ./mvnw clean test

      - name: Build application
        run: ./mvnw clean package -DskipTests
      - name: Debug GitHub OIDC claims
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Repository ID: $GITHUB_REPOSITORY_ID"
          echo "Repository owner ID: $GITHUB_REPOSITORY_OWNER_ID"
          echo "Ref: $GITHUB_REF"
          echo "Workflow: $GITHUB_WORKFLOW"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::844096318659:role/GitHubActionsPaymentGatewayECRRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          REGISTRY: 844096318659.dkr.ecr.us-east-1.amazonaws.com
          REPOSITORY: payment-gateway
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG